version: "3.3"
services:

  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - TZ=Europe/London
      - MYSQL_DATABASE=$DB_DATABASE
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASS
    volumes:
      - ./db_data:/config
    restart: always
    labels:
      - traefik.enable=false
    networks:
      - default

  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - DB_HOST=bookstack_db
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_DATABASE=$DB_DATABASE
      - APP_DEBUG=false
      - APP_URL=https://book.it-tf.ch
      - AUTH_METHOD=ldap
      - LDAP_SERVER=$LDAP_SERVER
      - LDAP_BASE_DN=$LDAP_BASE_DN
      - LDAP_DN=$LDAP_DN
      - LDAP_PASS=$LDAP_PASS
      - LDAP_USER_FILTER=(&(sAMAccountName=$${user}))
      - LDAP_VERSION=3 
    volumes:
      - ./app-data:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.bookstack_insecure.rule=Host(`book.it-tf.ch`)
      - traefik.http.routers.bookstack_insecure.entrypoints=web
      - traefik.http.routers.bookstack_insecure.middlewares=redirect@file

      - traefik.http.routers.bookstack.entrypoints=web-secure
      - traefik.http.routers.bookstack.rule=Host(`book.it-tf.ch`)
      - traefik.http.routers.bookstack.tls.certresolver=letsencrypt
      - traefik.http.services.bookstack.loadbalancer.server.port=80

      - traefik.docker.network=traefik-proxy
    restart: always
    depends_on:
      - bookstack_db
    networks:
      - traefik-proxy
      - default

networks:
  traefik-proxy:
    external: true
