version: '3.3'
services:
  kanboard:
    image: kanboard/kanboard:latest
    volumes:
      - ./kanboard_data:/var/www/app/data
      - ./kanboard_plugins:/var/www/app/plugins
      - ./kanboard_ssl:/etc/nginx/ssl
    networks: 
      - traefik-proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.kanboard.rule=Host(`board.it-tf.ch`)
      - traefik.http.routers.kanboard.entrypoints=web
      - traefik.http.services.kanboard.loadbalancer.server.port=80    
    restart: always               
networks:
  traefik-proxy:
    external: true
